name: CoffeeCodes
favicon: null
layout_spectrum: 0.37922
typography_spectrum: 0.528953
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#0A0A0A'
    - '#A98FCC'
    - '#426FB4'
    - '#662923'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
