analytics: {}
color:
  brandColors:
    - '#FFFFFF'
    - '#0A0A0A'
    - '#A98FCC'
    - '#426FB4'
    - '#662923'
  brandStrength: 0.3125
  lightness: 0.375
  rhythmicContrast: 0.646369
  saturation: 0.1875
cta: {}
layout_spectrum: 0.952702
name: CoffeeCodes
opengraph: {}
purpose: []
typography_spectrum: 0.528953
